apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: demo-email-alerts
  namespace: demo
  labels:
    app: demo-email-alerts
spec:
  route:
    groupBy: ["alertname", "namespace", "severity"]
    groupWait: 10s
    groupInterval: 30s
    repeatInterval: 12h
    receiver: demo-email
    routes:
    - receiver: demo-email
      matchers:
      - name: severity
        value: critical
        matchType: =
      continue: true
    - receiver: demo-email
      matchers:
      - name: severity
        value: warning
        matchType: =
  receivers:
  - name: demo-email
    emailConfigs:
    - to: tungduong22112004@gmail.com
      from: tungduong22112004@gmail.com
      smarthost: smtp.gmail.com:587
      authUsername: tungduong22112004@gmail.com
      authPassword:
        name: alertmanager-smtp-auth
        key: password
      requireTLS: true
      sendResolved: true
      headers:
      - key: Subject
        value: "[GitOps Demo] {{ .CommonLabels.alertname }}"
